const { EntitySchema } = require('typeorm');

const ReportEntity = new EntitySchema({
  name: 'Report',
  tableName: 'reports',
  columns: {
    id: {
      type: 'uuid',
      primary: true,
      generated: 'uuid',
    },
    child_id: {
      type: 'uuid',
    },
    report_type: {
      type: 'varchar',
      length: 20,
      default: 'WEEKLY',
    },
    content: {
      type: 'text',
    },
    ai_model: {
      type: 'varchar',
      length: 50,
      nullable: true,
    },
    ai_disclaimer: {
      type: 'text',
      nullable: true,
      default: 'This report was generated by AI and should be reviewed by a professional.',
    },
    period_start: {
      type: 'date',
    },
    period_end: {
      type: 'date',
    },
    created_at: {
      type: 'timestamptz',
      createDate: true,
    },
  },
  relations: {
    child: {
      type: 'many-to-one',
      target: 'User',
      joinColumn: { name: 'child_id' },
      onDelete: 'CASCADE',
    },
  },
});

module.exports = { ReportEntity };
